// 1. Bootstrap
// 2. Dùng bootstrap xây dựng trang web đơn giản
// 3. Dùng JS để đổ dữ liệu lên màn hình
// 
const data =[{
    "id": 1,
    "first_name": "Carla",
    "latest-chapter": 85,
    "image": "http://dummyimage.com/115x100.png/dddddd/000000"
  }, {
    "id": 2,
    "first_name": "Alard",
    "latest-chapter": 64,
    "image": "http://dummyimage.com/175x100.png/cc0000/ffffff"
  }, {
    "id": 3,
    "first_name": "Friedrick",
    "latest-chapter": 81,
    "image": "http://dummyimage.com/198x100.png/5fa2dd/ffffff"
  }, {
    "id": 4,
    "first_name": "Costa",
    "latest-chapter": 73,
    "image": "http://dummyimage.com/132x100.png/ff4444/ffffff"
  }, {
    "id": 5,
    "first_name": "Reinhard",
    "latest-chapter": 67,
    "image": "http://dummyimage.com/246x100.png/cc0000/ffffff"
  }, {
    "id": 6,
    "first_name": "Alexandro",
    "latest-chapter": 92,
    "image": "http://dummyimage.com/207x100.png/ff4444/ffffff"
  }, {
    "id": 7,
    "first_name": "Michale",
    "latest-chapter": 58,
    "image": "http://dummyimage.com/205x100.png/ff4444/ffffff"
  }, {
    "id": 8,
    "first_name": "Madonna",
    "latest-chapter": 61,
    "image": "http://dummyimage.com/100x100.png/ff4444/ffffff"
  }, {
    "id": 9,
    "first_name": "Anna-maria",
    "latest-chapter": 78,
    "image": "http://dummyimage.com/103x100.png/cc0000/ffffff"
  }, {
    "id": 10,
    "first_name": "Dolorita",
    "latest-chapter": 67,
    "image": "http://dummyimage.com/151x100.png/ff4444/ffffff"
  }, {
    "id": 11,
    "first_name": "Brianna",
    "latest-chapter": 64,
    "image": "http://dummyimage.com/236x100.png/ff4444/ffffff"
  }, {
    "id": 12,
    "first_name": "Kelci",
    "latest-chapter": 64,
    "image": "http://dummyimage.com/121x100.png/cc0000/ffffff"
  }, {
    "id": 13,
    "first_name": "Wendeline",
    "latest-chapter": 65,
    "image": "http://dummyimage.com/123x100.png/dddddd/000000"
  }, {
    "id": 14,
    "first_name": "Janessa",
    "latest-chapter": 85,
    "image": "http://dummyimage.com/120x100.png/dddddd/000000"
  }, {
    "id": 15,
    "first_name": "Kasey",
    "latest-chapter": 86,
    "image": "http://dummyimage.com/188x100.png/5fa2dd/ffffff"
  }, {
    "id": 16,
    "first_name": "Rowney",
    "latest-chapter": 51,
    "image": "http://dummyimage.com/234x100.png/dddddd/000000"
  }, {
    "id": 17,
    "first_name": "Boony",
    "latest-chapter": 57,
    "image": "http://dummyimage.com/104x100.png/5fa2dd/ffffff"
  }, {
    "id": 18,
    "first_name": "Araldo",
    "latest-chapter": 61,
    "image": "http://dummyimage.com/205x100.png/cc0000/ffffff"
  }, {
    "id": 19,
    "first_name": "Issi",
    "latest-chapter": 99,
    "image": "http://dummyimage.com/146x100.png/ff4444/ffffff"
  }, {
    "id": 20,
    "first_name": "Deb",
    "latest-chapter": 83,
    "image": "http://dummyimage.com/145x100.png/dddddd/000000"
  }, {
    "id": 21,
    "first_name": "Andy",
    "latest-chapter": 100,
    "image": "http://dummyimage.com/131x100.png/dddddd/000000"
  }, {
    "id": 22,
    "first_name": "Christian",
    "latest-chapter": 94,
    "image": "http://dummyimage.com/243x100.png/5fa2dd/ffffff"
  }, {
    "id": 23,
    "first_name": "Pippo",
    "latest-chapter": 74,
    "image": "http://dummyimage.com/178x100.png/5fa2dd/ffffff"
  }, {
    "id": 24,
    "first_name": "Alanna",
    "latest-chapter": 69,
    "image": "http://dummyimage.com/113x100.png/ff4444/ffffff"
  }, {
    "id": 25,
    "first_name": "Blondie",
    "latest-chapter": 56,
    "image": "http://dummyimage.com/229x100.png/cc0000/ffffff"
  }, {
    "id": 26,
    "first_name": "Berry",
    "latest-chapter": 92,
    "image": "http://dummyimage.com/202x100.png/ff4444/ffffff"
  }, {
    "id": 27,
    "first_name": "Chiarra",
    "latest-chapter": 97,
    "image": "http://dummyimage.com/249x100.png/dddddd/000000"
  }, {
    "id": 28,
    "first_name": "Giavani",
    "latest-chapter": 94,
    "image": "http://dummyimage.com/164x100.png/5fa2dd/ffffff"
  }, {
    "id": 29,
    "first_name": "Amabelle",
    "latest-chapter": 71,
    "image": "http://dummyimage.com/109x100.png/cc0000/ffffff"
  }, {
    "id": 30,
    "first_name": "Morey",
    "latest-chapter": 92,
    "image": "http://dummyimage.com/142x100.png/5fa2dd/ffffff"
  }, {
    "id": 31,
    "first_name": "Debbi",
    "latest-chapter": 65,
    "image": "http://dummyimage.com/136x100.png/5fa2dd/ffffff"
  }, {
    "id": 32,
    "first_name": "Janette",
    "latest-chapter": 89,
    "image": "http://dummyimage.com/186x100.png/5fa2dd/ffffff"
  }, {
    "id": 33,
    "first_name": "Corrina",
    "latest-chapter": 99,
    "image": "http://dummyimage.com/145x100.png/5fa2dd/ffffff"
  }, {
    "id": 34,
    "first_name": "Dynah",
    "latest-chapter": 79,
    "image": "http://dummyimage.com/245x100.png/cc0000/ffffff"
  }, {
    "id": 35,
    "first_name": "L;urette",
    "latest-chapter": 71,
    "image": "http://dummyimage.com/169x100.png/dddddd/000000"
  }, {
    "id": 36,
    "first_name": "Wolfie",
    "latest-chapter": 60,
    "image": "http://dummyimage.com/200x100.png/5fa2dd/ffffff"
  }, {
    "id": 37,
    "first_name": "Steven",
    "latest-chapter": 55,
    "image": "http://dummyimage.com/103x100.png/ff4444/ffffff"
  }, {
    "id": 38,
    "first_name": "Ardys",
    "latest-chapter": 82,
    "image": "http://dummyimage.com/198x100.png/dddddd/000000"
  }, {
    "id": 39,
    "first_name": "Ruttger",
    "latest-chapter": 60,
    "image": "http://dummyimage.com/250x100.png/5fa2dd/ffffff"
  }, {
    "id": 40,
    "first_name": "Ashley",
    "latest-chapter": 85,
    "image": "http://dummyimage.com/246x100.png/5fa2dd/ffffff"
  }, {
    "id": 41,
    "first_name": "Westley",
    "latest-chapter": 84,
    "image": "http://dummyimage.com/120x100.png/5fa2dd/ffffff"
  }, {
    "id": 42,
    "first_name": "Marlyn",
    "latest-chapter": 50,
    "image": "http://dummyimage.com/162x100.png/dddddd/000000"
  }, {
    "id": 43,
    "first_name": "Tedie",
    "latest-chapter": 50,
    "image": "http://dummyimage.com/172x100.png/dddddd/000000"
  }, {
    "id": 44,
    "first_name": "Cathyleen",
    "latest-chapter": 51,
    "image": "http://dummyimage.com/172x100.png/5fa2dd/ffffff"
  }, {
    "id": 45,
    "first_name": "Emmit",
    "latest-chapter": 70,
    "image": "http://dummyimage.com/211x100.png/cc0000/ffffff"
  }, {
    "id": 46,
    "first_name": "Minny",
    "latest-chapter": 69,
    "image": "http://dummyimage.com/243x100.png/cc0000/ffffff"
  }, {
    "id": 47,
    "first_name": "Kailey",
    "latest-chapter": 80,
    "image": "http://dummyimage.com/157x100.png/dddddd/000000"
  }, {
    "id": 48,
    "first_name": "Dorris",
    "latest-chapter": 51,
    "image": "http://dummyimage.com/105x100.png/cc0000/ffffff"
  }, {
    "id": 49,
    "first_name": "Joscelin",
    "latest-chapter": 66,
    "image": "http://dummyimage.com/144x100.png/cc0000/ffffff"
  }, {
    "id": 50,
    "first_name": "Torie",
    "latest-chapter": 82,
    "image": "http://dummyimage.com/221x100.png/5fa2dd/ffffff"
  }, {
    "id": 51,
    "first_name": "Winny",
    "latest-chapter": 78,
    "image": "http://dummyimage.com/121x100.png/cc0000/ffffff"
  }, {
    "id": 52,
    "first_name": "Carly",
    "latest-chapter": 80,
    "image": "http://dummyimage.com/132x100.png/cc0000/ffffff"
  }, {
    "id": 53,
    "first_name": "Portie",
    "latest-chapter": 51,
    "image": "http://dummyimage.com/131x100.png/cc0000/ffffff"
  }, {
    "id": 54,
    "first_name": "Corby",
    "latest-chapter": 63,
    "image": "http://dummyimage.com/231x100.png/dddddd/000000"
  }, {
    "id": 55,
    "first_name": "Job",
    "latest-chapter": 97,
    "image": "http://dummyimage.com/130x100.png/dddddd/000000"
  }, {
    "id": 56,
    "first_name": "Lexis",
    "latest-chapter": 57,
    "image": "http://dummyimage.com/246x100.png/cc0000/ffffff"
  }, {
    "id": 57,
    "first_name": "Barrett",
    "latest-chapter": 94,
    "image": "http://dummyimage.com/116x100.png/cc0000/ffffff"
  }, {
    "id": 58,
    "first_name": "Pam",
    "latest-chapter": 61,
    "image": "http://dummyimage.com/250x100.png/5fa2dd/ffffff"
  }, {
    "id": 59,
    "first_name": "Timmy",
    "latest-chapter": 82,
    "image": "http://dummyimage.com/183x100.png/ff4444/ffffff"
  }, {
    "id": 60,
    "first_name": "Zacharia",
    "latest-chapter": 88,
    "image": "http://dummyimage.com/182x100.png/5fa2dd/ffffff"
  }, {
    "id": 61,
    "first_name": "Far",
    "latest-chapter": 86,
    "image": "http://dummyimage.com/164x100.png/5fa2dd/ffffff"
  }, {
    "id": 62,
    "first_name": "Merry",
    "latest-chapter": 77,
    "image": "http://dummyimage.com/198x100.png/cc0000/ffffff"
  }, {
    "id": 63,
    "first_name": "Bengt",
    "latest-chapter": 67,
    "image": "http://dummyimage.com/179x100.png/ff4444/ffffff"
  }, {
    "id": 64,
    "first_name": "Marika",
    "latest-chapter": 80,
    "image": "http://dummyimage.com/163x100.png/cc0000/ffffff"
  }, {
    "id": 65,
    "first_name": "Wylma",
    "latest-chapter": 52,
    "image": "http://dummyimage.com/234x100.png/dddddd/000000"
  }, {
    "id": 66,
    "first_name": "Hurley",
    "latest-chapter": 56,
    "image": "http://dummyimage.com/147x100.png/dddddd/000000"
  }, {
    "id": 67,
    "first_name": "Hermann",
    "latest-chapter": 74,
    "image": "http://dummyimage.com/112x100.png/5fa2dd/ffffff"
  }, {
    "id": 68,
    "first_name": "Mannie",
    "latest-chapter": 65,
    "image": "http://dummyimage.com/148x100.png/dddddd/000000"
  }, {
    "id": 69,
    "first_name": "Betsey",
    "latest-chapter": 97,
    "image": "http://dummyimage.com/221x100.png/5fa2dd/ffffff"
  }, {
    "id": 70,
    "first_name": "Dodi",
    "latest-chapter": 75,
    "image": "http://dummyimage.com/147x100.png/5fa2dd/ffffff"
  }, {
    "id": 71,
    "first_name": "Chaim",
    "latest-chapter": 90,
    "image": "http://dummyimage.com/219x100.png/5fa2dd/ffffff"
  }, {
    "id": 72,
    "first_name": "Elvera",
    "latest-chapter": 86,
    "image": "http://dummyimage.com/237x100.png/ff4444/ffffff"
  }, {
    "id": 73,
    "first_name": "Brittany",
    "latest-chapter": 57,
    "image": "http://dummyimage.com/191x100.png/ff4444/ffffff"
  }, {
    "id": 74,
    "first_name": "Emanuel",
    "latest-chapter": 99,
    "image": "http://dummyimage.com/155x100.png/ff4444/ffffff"
  }, {
    "id": 75,
    "first_name": "Lavena",
    "latest-chapter": 85,
    "image": "http://dummyimage.com/240x100.png/ff4444/ffffff"
  }, {
    "id": 76,
    "first_name": "Ruthie",
    "latest-chapter": 52,
    "image": "http://dummyimage.com/180x100.png/cc0000/ffffff"
  }, {
    "id": 77,
    "first_name": "Marcie",
    "latest-chapter": 61,
    "image": "http://dummyimage.com/236x100.png/ff4444/ffffff"
  }, {
    "id": 78,
    "first_name": "Mellicent",
    "latest-chapter": 69,
    "image": "http://dummyimage.com/184x100.png/dddddd/000000"
  }, {
    "id": 79,
    "first_name": "Pat",
    "latest-chapter": 64,
    "image": "http://dummyimage.com/107x100.png/cc0000/ffffff"
  }, {
    "id": 80,
    "first_name": "Mariellen",
    "latest-chapter": 76,
    "image": "http://dummyimage.com/144x100.png/5fa2dd/ffffff"
  }, {
    "id": 81,
    "first_name": "Cara",
    "latest-chapter": 97,
    "image": "http://dummyimage.com/218x100.png/5fa2dd/ffffff"
  }, {
    "id": 82,
    "first_name": "Kimble",
    "latest-chapter": 53,
    "image": "http://dummyimage.com/102x100.png/ff4444/ffffff"
  }, {
    "id": 83,
    "first_name": "Colin",
    "latest-chapter": 70,
    "image": "http://dummyimage.com/166x100.png/cc0000/ffffff"
  }, {
    "id": 84,
    "first_name": "Layton",
    "latest-chapter": 91,
    "image": "http://dummyimage.com/153x100.png/dddddd/000000"
  }, {
    "id": 85,
    "first_name": "Melita",
    "latest-chapter": 98,
    "image": "http://dummyimage.com/139x100.png/5fa2dd/ffffff"
  }, {
    "id": 86,
    "first_name": "Aleen",
    "latest-chapter": 84,
    "image": "http://dummyimage.com/114x100.png/dddddd/000000"
  }, {
    "id": 87,
    "first_name": "Winnah",
    "latest-chapter": 83,
    "image": "http://dummyimage.com/110x100.png/dddddd/000000"
  }, {
    "id": 88,
    "first_name": "Carmela",
    "latest-chapter": 91,
    "image": "http://dummyimage.com/154x100.png/5fa2dd/ffffff"
  }, {
    "id": 89,
    "first_name": "Goraud",
    "latest-chapter": 55,
    "image": "http://dummyimage.com/137x100.png/dddddd/000000"
  }, {
    "id": 90,
    "first_name": "Sayre",
    "latest-chapter": 96,
    "image": "http://dummyimage.com/153x100.png/ff4444/ffffff"
  }, {
    "id": 91,
    "first_name": "Haywood",
    "latest-chapter": 95,
    "image": "http://dummyimage.com/176x100.png/dddddd/000000"
  }, {
    "id": 92,
    "first_name": "Kermy",
    "latest-chapter": 59,
    "image": "http://dummyimage.com/203x100.png/5fa2dd/ffffff"
  }, {
    "id": 93,
    "first_name": "Brooke",
    "latest-chapter": 75,
    "image": "http://dummyimage.com/135x100.png/5fa2dd/ffffff"
  }, {
    "id": 94,
    "first_name": "Erl",
    "latest-chapter": 88,
    "image": "http://dummyimage.com/136x100.png/dddddd/000000"
  }, {
    "id": 95,
    "first_name": "Ceciley",
    "latest-chapter": 70,
    "image": "http://dummyimage.com/211x100.png/cc0000/ffffff"
  }, {
    "id": 96,
    "first_name": "Alfie",
    "latest-chapter": 90,
    "image": "http://dummyimage.com/176x100.png/cc0000/ffffff"
  }, {
    "id": 97,
    "first_name": "Gherardo",
    "latest-chapter": 61,
    "image": "http://dummyimage.com/226x100.png/5fa2dd/ffffff"
  }, {
    "id": 98,
    "first_name": "Corene",
    "latest-chapter": 58,
    "image": "http://dummyimage.com/127x100.png/cc0000/ffffff"
  }, {
    "id": 99,
    "first_name": "De",
    "latest-chapter": 96,
    "image": "http://dummyimage.com/122x100.png/ff4444/ffffff"
  }, {
    "id": 100,
    "first_name": "Cull",
    "latest-chapter": 76,
    "image": "http://dummyimage.com/178x100.png/ff4444/ffffff"
  }]

  const $booklist = document.getElementById('booklist');
  $booklist.innerHTML = data.map(({name, latest_chapter,image}) =>{
    return`
    <div class="col-3 mb-3">
                <div class="card">
                    <img class="card-img-top" src="${image}" alt="">
                    <div class="card-body">
                        <b class="card-title">${name}</b>
                        <p class="class-text">${latest_chapter}</p>
                        <a href="#" class="btn btn-ouline-primary btn-sm"></a>
                        <a href="#" class="btn btn-ouline-danger btn-sm"></a>
                    </div>
                </div>
            </div>`;

  }
  ).join('');